### ISSUE TITLE
Rarely-occurring offset between node graph appearance and pointer interactions

### ISSUE THREAD

**Issue by Synthoid** [GraphiteEditor/Graphite#2869]
It appears that the node graph's selection areas are offset to the right of node visuals. This causes nodes to be dragged around when you think you're interacting with the node's port, making it frustrating to connect nodes in the graph editor unless you know about the offset.

I'm seeing this on an M4 MacBook Pro running the latest version of Chrome (Version 138.0.7204.94).

https://github.com/user-attachments/assets/003fb7ef-3af1-41fc-a03b-6e16dbbad97c

**Comment by Keavon** [comment]
Is this happening for you on <https://editor.graphite.rs> or are you using dev?

We've been observing this for a few weeks, but it is hard to pin down because it seems to happen randomly and somewhat infrequently, with no discernible cause. If you or anyone else notices some kind of cause-and-effect relationship, please report theories.

When it happens, the solution is to reload the browser window.

**Comment by Synthoid** [comment]
I'm using [https://editor.graphite.rs](https://editor.graphite.rs). And yeah, I just closed and reopened the window to see what would happen and that seems to have fixed the offset. Not sure what caused it initially as I hadn't done much in the file, just uploaded a raster image and messed around with the pen tool a little bit.

**Comment by Keavon** [comment]
If anybody notices this occurring ever again on https://dev.graphite.rs, please report about it here. It might have been fixed, but it's rare enough that we'll need reports to the contrary, or otherwise keep an eye on it for a few months and then close this.

**Comment by timon-schelling** [comment]
not fixed see https://github.com/GraphiteEditor/Graphite/issues/3291

**Comment by timon-schelling** [comment]
closing in favor of #3244
see reproduction in that issue.
